LIFE STYLE PREDIICTION

In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

In [2]:
os.chdir('D:\MEGHA')
os.getcwd()

'D:\\MEGHA'

data collection and processing

In [3]:
# loading csv data to pandas dataframe
life_data = pd.read_csv("data.csv")

In [5]:
life_data.head()

1  FRUITS_VEGGIES DAILY_STRESS  PLACES_VISITED  CORE_CIRCLE  \
0  07-07-2015               3            2               2            5   
1  07-07-2015               2            3               4            3   
2  07-07-2015               2            3               3            4   
3  07-07-2015               3            3              10            3   
4  07-07-2015               5            1               3            3   

   SUPPORTING_OTHERS  SOCIAL_NETWORK  ACHIEVEMENT  DONATION  BMI_RANGE  ...  \
0                  0               5            2         0          1  ...   
1                  8              10            5         2          2  ...   
2                  4              10            3         2          2  ...   
3                 10               7            2         5          2  ...   
4                 10               4            2         4          2  ...   

   SLEEP_HOURS  LOST_VACATION  DAILY_SHOUTING  SUFFICIENT_INCOME  \
0            7              5               5                  1   
1            8              2               2                  2   
2            8             10               2                  2   
3            5              7               5                  1   
4            7              0               0                  2   

   PERSONAL_AWARDS  TIME_FOR_PASSION  WEEKLY_MEDITATION         AGE  GENDER  \
0                4                 0                  5    36 to 50  Female   
1                3                 2                  6    36 to 50  Female   
2                4                 8                  3    36 to 50  Female   
3                5                 2                  0  51 or more  Female   
4                8                 1                  5  51 or more  Female   

   WORK_LIFE_BALANCE_SCORE  
0                    609.5  
1                    655.6  
2                    631.6  
3                    622.7  
4                    663.9  

[5 rows x 24 columns]

In [6]:
life_data.tail()

1  FRUITS_VEGGIES DAILY_STRESS  PLACES_VISITED  CORE_CIRCLE  \
15967  3/14/21 5:42               3            3               0            4   
15968  3/14/21 6:30               3            3               6            8   
15969  3/14/21 8:35               4            3               0           10   
15970  3/14/21 8:43               1            1              10            8   
15971  3/14/21 9:03               5            4               0            2   

       SUPPORTING_OTHERS  SOCIAL_NETWORK  ACHIEVEMENT  DONATION  BMI_RANGE  \
15967                  0              10            0         4          2   
15968                  7               4            6         3          1   
15969                 10               8            6         5          1   
15970                  2               7            3         2          1   
15971                 10              10            5         1          2   

       ...  SLEEP_HOURS  LOST_VACATION  DAILY_SHOUTING  SUFFICIENT_INCOME  \
15967  ...            7              0               1                  1   
15968  ...            6              0               0                  2   
15969  ...            7              0               1                  2   
15970  ...            8              7               2                  2   
15971  ...            8              5               2                  2   

       PERSONAL_AWARDS  TIME_FOR_PASSION  WEEKLY_MEDITATION         AGE  \
15967                5                 2                  5  51 or more   
15968               10                 5                  8    21 to 35   
15969               10                 1                 10    21 to 35   
15970                1                 6                  8    21 to 35   
15971                1                 8                  4    21 to 35   

       GENDER  WORK_LIFE_BALANCE_SCORE  
15967  Female                    644.5  
15968  Female                    714.9  
15969    Male                    716.6  
15970  Female                    682.0  
15971  Female                    651.4  

[5 rows x 24 columns]

In [7]:
sum=life_data.isnull().sum()
print (sum)

1                          0
FRUITS_VEGGIES             0
DAILY_STRESS               0
PLACES_VISITED             0
CORE_CIRCLE                0
SUPPORTING_OTHERS          0
SOCIAL_NETWORK             0
ACHIEVEMENT                0
DONATION                   0
BMI_RANGE                  0
TODO_COMPLETED             0
FLOW                       0
DAILY_STEPS                0
LIVE_VISION                0
SLEEP_HOURS                0
LOST_VACATION              0
DAILY_SHOUTING             0
SUFFICIENT_INCOME          0
PERSONAL_AWARDS            0
TIME_FOR_PASSION           0
WEEKLY_MEDITATION          0
AGE                        0
GENDER                     0
WORK_LIFE_BALANCE_SCORE    0
dtype: int64


In [8]:
life_data.shape

(15972, 24)

In [9]:
#getting some info about data
life_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15972 entries, 0 to 15971
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   1                        15972 non-null  object 
 1   FRUITS_VEGGIES           15972 non-null  int64  
 2   DAILY_STRESS             15972 non-null  object 
 3   PLACES_VISITED           15972 non-null  int64  
 4   CORE_CIRCLE              15972 non-null  int64  
 5   SUPPORTING_OTHERS        15972 non-null  int64  
 6   SOCIAL_NETWORK           15972 non-null  int64  
 7   ACHIEVEMENT              15972 non-null  int64  
 8   DONATION                 15972 non-null  int64  
 9   BMI_RANGE                15972 non-null  int64  
 10  TODO_COMPLETED           15972 non-null  int64  
 11  FLOW                     15972 non-null  int64  
 12  DAILY_STEPS              15972 non-null  int64  
 13  LIVE_VISION              15972 non-null  int64  
 14  SLEEP_HOURS           

In [9]:
#as the daily_stress,Gender,Age object is categorical and the value should be converted to numeric 

In [10]:
#checking for existing missing values
life_data.isnull().sum()

1                          0
FRUITS_VEGGIES             0
DAILY_STRESS               0
PLACES_VISITED             0
CORE_CIRCLE                0
SUPPORTING_OTHERS          0
SOCIAL_NETWORK             0
ACHIEVEMENT                0
DONATION                   0
BMI_RANGE                  0
TODO_COMPLETED             0
FLOW                       0
DAILY_STEPS                0
LIVE_VISION                0
SLEEP_HOURS                0
LOST_VACATION              0
DAILY_SHOUTING             0
SUFFICIENT_INCOME          0
PERSONAL_AWARDS            0
TIME_FOR_PASSION           0
WEEKLY_MEDITATION          0
AGE                        0
GENDER                     0
WORK_LIFE_BALANCE_SCORE    0
dtype: int64

In [11]:
# statistical measure about data
life_data.describe()

FRUITS_VEGGIES  PLACES_VISITED   CORE_CIRCLE  SUPPORTING_OTHERS  \
count    15972.000000    15972.000000  15972.000000       15972.000000   
mean         2.922677        5.232970      5.508077           5.616454   
std          1.442694        3.311912      2.840334           3.242021   
min          0.000000        0.000000      0.000000           0.000000   
25%          2.000000        2.000000      3.000000           3.000000   
50%          3.000000        5.000000      5.000000           5.000000   
75%          4.000000        8.000000      8.000000          10.000000   
max          5.000000       10.000000     10.000000          10.000000   

       SOCIAL_NETWORK   ACHIEVEMENT      DONATION     BMI_RANGE  \
count    15972.000000  15972.000000  15972.000000  15972.000000   
mean         6.474267      4.000751      2.715314      1.410656   
std          3.086672      2.755837      1.851586      0.491968   
min          0.000000      0.000000      0.000000      1.000000   
25%          4.000000      2.000000      1.000000      1.000000   
50%          6.000000      3.000000      3.000000      1.000000   
75%         10.000000      6.000000      5.000000      2.000000   
max         10.000000     10.000000      5.000000      2.000000   

       TODO_COMPLETED          FLOW   DAILY_STEPS   LIVE_VISION   SLEEP_HOURS  \
count    15972.000000  15972.000000  15972.000000  15972.000000  15972.000000   
mean         5.745993      3.194778      5.703606      3.752129      7.042888   
std          2.624097      2.357518      2.891013      3.230987      1.199044   
min          0.000000      0.000000      1.000000      0.000000      1.000000   
25%          4.000000      1.000000      3.000000      1.000000      6.000000   
50%          6.000000      3.000000      5.000000      3.000000      7.000000   
75%          8.000000      5.000000      8.000000      5.000000      8.000000   
max         10.000000     10.000000     10.000000     10.000000     10.000000   

       LOST_VACATION  DAILY_SHOUTING  SUFFICIENT_INCOME  PERSONAL_AWARDS  \
count   15972.000000    15972.000000       15972.000000     15972.000000   
mean        2.898886        2.930879           1.728963         5.711558   
std         3.692180        2.676301           0.444509         3.089630   
min         0.000000        0.000000           1.000000         0.000000   
25%         0.000000        1.000000           1.000000         3.000000   
50%         0.000000        2.000000           2.000000         5.000000   
75%         5.000000        4.000000           2.000000         9.000000   
max        10.000000       10.000000           2.000000        10.000000   

       TIME_FOR_PASSION  WEEKLY_MEDITATION  WORK_LIFE_BALANCE_SCORE  
count      15972.000000       15972.000000             15972.000000  
mean           3.326572           6.233346               666.751503  
std            2.729293           3.016571                45.019868  
min            0.000000           0.000000               480.000000  
25%            1.000000           4.000000               636.000000  
50%            3.000000           7.000000               667.700000  
75%            5.000000          10.000000               698.500000  
max           10.000000          10.000000               820.200000

In [12]:
life_data1 = life_data.drop(['1','CORE_CIRCLE','DONATION','FLOW','LOST_VACATION','PERSONAL_AWARDS'], axis=1)

In [13]:
life_data1

FRUITS_VEGGIES DAILY_STRESS  PLACES_VISITED  SUPPORTING_OTHERS  \
0                   3            2               2                  0   
1                   2            3               4                  8   
2                   2            3               3                  4   
3                   3            3              10                 10   
4                   5            1               3                 10   
...               ...          ...             ...                ...   
15967               3            3               0                  0   
15968               3            3               6                  7   
15969               4            3               0                 10   
15970               1            1              10                  2   
15971               5            4               0                 10   

       SOCIAL_NETWORK  ACHIEVEMENT  BMI_RANGE  TODO_COMPLETED  DAILY_STEPS  \
0                   5            2          1               6            5   
1                  10            5          2               5            5   
2                  10            3          2               2            4   
3                   7            2          2               3            5   
4                   4            2          2               5            5   
...               ...          ...        ...             ...          ...   
15967              10            0          2               8           10   
15968               4            6          1               7            6   
15969               8            6          1               7            5   
15970               7            3          1               6            1   
15971              10            5          2               7            1   

       LIVE_VISION  SLEEP_HOURS  DAILY_SHOUTING  SUFFICIENT_INCOME  \
0                0            7               5                  1   
1                5            8               2                  2   
2                5            8               2                  2   
3                0            5               5                  1   
4                0            7               0                  2   
...            ...          ...             ...                ...   
15967            7            7               1                  1   
15968            5            6               0                  2   
15969            2            7               1                  2   
15970            5            8               2                  2   
15971            5            8               2                  2   

       TIME_FOR_PASSION  WEEKLY_MEDITATION         AGE  GENDER  \
0                     0                  5    36 to 50  Female   
1                     2                  6    36 to 50  Female   
2                     8                  3    36 to 50  Female   
3                     2                  0  51 or more  Female   
4                     1                  5  51 or more  Female   
...                 ...                ...         ...     ...   
15967                 2                  5  51 or more  Female   
15968                 5                  8    21 to 35  Female   
15969                 1                 10    21 to 35    Male   
15970                 6                  8    21 to 35  Female   
15971                 8                  4    21 to 35  Female   

       WORK_LIFE_BALANCE_SCORE  
0                        609.5  
1                        655.6  
2                        631.6  
3                        622.7  
4                        663.9  
...                        ...  
15967                    644.5  
15968                    714.9  
15969                    716.6  
15970                    682.0  
15971                    651.4  

[15972 rows x 18 columns]

In [14]:
life_data1['FRUITS_VEGGIES'].unique()

array([3, 2, 5, 4, 1, 0], dtype=int64)

In [16]:
life_data1['PLACES_VISITED'].unique()

array([ 2,  4,  3, 10,  5,  6,  7,  0,  8,  1,  9], dtype=int64)

In [17]:
life_data1['SUPPORTING_OTHERS'].unique()

array([ 0,  8,  4, 10,  5,  3,  1,  2,  6,  7,  9], dtype=int64)

In [18]:
life_data1['SOCIAL_NETWORK'].unique()

array([ 5, 10,  7,  4,  3,  1,  2,  8,  6,  9,  0], dtype=int64)

In [19]:
life_data1['ACHIEVEMENT'].unique()

array([ 2,  5,  3,  4,  0,  1,  6, 10,  8,  7,  9], dtype=int64)

In [20]:
life_data1['DAILY_STRESS'].unique()

array(['2', '3', '1', '4', '5', '0', '01-01-2000'], dtype=object)

In [21]:
#to fix this before replacing it,it should be converted into null value.
life_data1=life_data1.replace('01-01-2000',np.nan)
life_data1['DAILY_STRESS'].unique()

array(['2', '3', '1', '4', '5', '0', nan], dtype=object)

In [22]:
life_data1['DAILY_STRESS'].unique()

array(['2', '3', '1', '4', '5', '0', nan], dtype=object)

In [23]:
life_data1['DAILY_STRESS'].fillna(value=0,inplace=True)

In [23]:
life_data1['DAILY_STRESS'].unique()


array(['2', '3', '1', '4', '5', '0', 0], dtype=object)

In [24]:
life_data1['DAILY_STRESS']=life_data1['DAILY_STRESS'].astype(int)
life_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15972 entries, 0 to 15971
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   FRUITS_VEGGIES           15972 non-null  int64  
 1   DAILY_STRESS             15972 non-null  int32  
 2   PLACES_VISITED           15972 non-null  int64  
 3   SUPPORTING_OTHERS        15972 non-null  int64  
 4   SOCIAL_NETWORK           15972 non-null  int64  
 5   ACHIEVEMENT              15972 non-null  int64  
 6   BMI_RANGE                15972 non-null  int64  
 7   TODO_COMPLETED           15972 non-null  int64  
 8   DAILY_STEPS              15972 non-null  int64  
 9   LIVE_VISION              15972 non-null  int64  
 10  SLEEP_HOURS              15972 non-null  int64  
 11  DAILY_SHOUTING           15972 non-null  int64  
 12  SUFFICIENT_INCOME        15972 non-null  int64  
 13  TIME_FOR_PASSION         15972 non-null  int64  
 14  WEEKLY_MEDITATION     

In [25]:
life_data1['AGE'].unique()

array(['36 to 50', '51 or more', '21 to 35', 'Less than 20'], dtype=object)

In [26]:
life_data1['AGE'].mode()

0    21 to 35
Name: AGE, dtype: object

In [27]:
life_data1['GENDER']

0        Female
1        Female
2        Female
3        Female
4        Female
          ...  
15967    Female
15968    Female
15969      Male
15970    Female
15971    Female
Name: GENDER, Length: 15972, dtype: object

In [28]:
life_data1.loc[life_data1["AGE"]=="Less than 20","AGE"]=0
life_data1.loc[life_data1["AGE"]=="21 to 35","AGE"]=1
life_data1.loc[life_data1["AGE"]=="36 to 50","AGE"]=2
life_data1.loc[life_data1["AGE"]=="51 or more","AGE"]=3
life_data1.head()

FRUITS_VEGGIES  DAILY_STRESS  PLACES_VISITED  SUPPORTING_OTHERS  \
0               3             2               2                  0   
1               2             3               4                  8   
2               2             3               3                  4   
3               3             3              10                 10   
4               5             1               3                 10   

   SOCIAL_NETWORK  ACHIEVEMENT  BMI_RANGE  TODO_COMPLETED  DAILY_STEPS  \
0               5            2          1               6            5   
1              10            5          2               5            5   
2              10            3          2               2            4   
3               7            2          2               3            5   
4               4            2          2               5            5   

   LIVE_VISION  SLEEP_HOURS  DAILY_SHOUTING  SUFFICIENT_INCOME  \
0            0            7               5                  1   
1            5            8               2                  2   
2            5            8               2                  2   
3            0            5               5                  1   
4            0            7               0                  2   

   TIME_FOR_PASSION  WEEKLY_MEDITATION AGE  GENDER  WORK_LIFE_BALANCE_SCORE  
0                 0                  5   2  Female                    609.5  
1                 2                  6   2  Female                    655.6  
2                 8                  3   2  Female                    631.6  
3                 2                  0   3  Female                    622.7  
4                 1                  5   3  Female                    663.9

In [32]:
life_data1['GENDER'].unique()

array([1, 0])

In [33]:
#CONVERT GENDER TO NUMBER MALE-->0,FEMALE--->1
life_data1.loc[life_data1["GENDER"]=="Male","GENDER"]=0
life_data1.loc[life_data1["GENDER"]=="Female","GENDER"]=1
life_data1.head()

FRUITS_VEGGIES  DAILY_STRESS  PLACES_VISITED  SUPPORTING_OTHERS  \
0               3             2               2                  0   
1               2             3               4                  8   
2               2             3               3                  4   
3               3             3              10                 10   
4               5             1               3                 10   

   SOCIAL_NETWORK  ACHIEVEMENT  BMI_RANGE  TODO_COMPLETED  DAILY_STEPS  \
0               5            2          1               6            5   
1              10            5          2               5            5   
2              10            3          2               2            4   
3               7            2          2               3            5   
4               4            2          2               5            5   

   LIVE_VISION  SLEEP_HOURS  DAILY_SHOUTING  SUFFICIENT_INCOME  \
0            0            7               5                  1   
1            5            8               2                  2   
2            5            8               2                  2   
3            0            5               5                  1   
4            0            7               0                  2   

   TIME_FOR_PASSION  WEEKLY_MEDITATION AGE  GENDER  WORK_LIFE_BALANCE_SCORE  
0                 0                  5   2       1                    609.5  
1                 2                  6   2       1                    655.6  
2                 8                  3   2       1                    631.6  
3                 2                  0   3       1                    622.7  
4                 1                  5   3       1                    663.9

In [34]:
life_data1['GENDER']=life_data1['GENDER'].astype(int)
life_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15972 entries, 0 to 15971
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   FRUITS_VEGGIES           15972 non-null  int64  
 1   DAILY_STRESS             15972 non-null  int32  
 2   PLACES_VISITED           15972 non-null  int64  
 3   SUPPORTING_OTHERS        15972 non-null  int64  
 4   SOCIAL_NETWORK           15972 non-null  int64  
 5   ACHIEVEMENT              15972 non-null  int64  
 6   BMI_RANGE                15972 non-null  int64  
 7   TODO_COMPLETED           15972 non-null  int64  
 8   DAILY_STEPS              15972 non-null  int64  
 9   LIVE_VISION              15972 non-null  int64  
 10  SLEEP_HOURS              15972 non-null  int64  
 11  DAILY_SHOUTING           15972 non-null  int64  
 12  SUFFICIENT_INCOME        15972 non-null  int64  
 13  TIME_FOR_PASSION         15972 non-null  int64  
 14  WEEKLY_MEDITATION     

In [35]:
life_data1['AGE']=life_data1['AGE'].astype(int)
life_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15972 entries, 0 to 15971
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   FRUITS_VEGGIES           15972 non-null  int64  
 1   DAILY_STRESS             15972 non-null  int32  
 2   PLACES_VISITED           15972 non-null  int64  
 3   SUPPORTING_OTHERS        15972 non-null  int64  
 4   SOCIAL_NETWORK           15972 non-null  int64  
 5   ACHIEVEMENT              15972 non-null  int64  
 6   BMI_RANGE                15972 non-null  int64  
 7   TODO_COMPLETED           15972 non-null  int64  
 8   DAILY_STEPS              15972 non-null  int64  
 9   LIVE_VISION              15972 non-null  int64  
 10  SLEEP_HOURS              15972 non-null  int64  
 11  DAILY_SHOUTING           15972 non-null  int64  
 12  SUFFICIENT_INCOME        15972 non-null  int64  
 13  TIME_FOR_PASSION         15972 non-null  int64  
 14  WEEKLY_MEDITATION     

In [36]:
life_data1.dtypes

FRUITS_VEGGIES               int64
DAILY_STRESS                 int32
PLACES_VISITED               int64
SUPPORTING_OTHERS            int64
SOCIAL_NETWORK               int64
ACHIEVEMENT                  int64
BMI_RANGE                    int64
TODO_COMPLETED               int64
DAILY_STEPS                  int64
LIVE_VISION                  int64
SLEEP_HOURS                  int64
DAILY_SHOUTING               int64
SUFFICIENT_INCOME            int64
TIME_FOR_PASSION             int64
WEEKLY_MEDITATION            int64
AGE                          int32
GENDER                       int32
WORK_LIFE_BALANCE_SCORE    float64
dtype: object

In [37]:
life_data1['DAILY_STRESS'].mean()

2.791510142749812

In [35]:
life_data1['DAILY_STRESS'].fillna(life_data1['DAILY_STRESS'].mean())

0        2
1        3
2        3
3        3
4        1
        ..
15967    3
15968    3
15969    3
15970    1
15971    4
Name: DAILY_STRESS, Length: 15972, dtype: int32

In [38]:
life_data1['AGE'].unique()

array([2, 3, 1, 0])

In [39]:
# checking the distribution of target variable
life_data1['WORK_LIFE_BALANCE_SCORE'].value_counts()

641.4    75
660.5    57
670.7    37
696.4    37
675.8    36
         ..
794.8     1
562.1     1
555.6     1
531.0     1
790.5     1
Name: WORK_LIFE_BALANCE_SCORE, Length: 1696, dtype: int64

In [40]:
#splitting features and target
X = life_data1.drop(columns='WORK_LIFE_BALANCE_SCORE', axis=1)
Y = life_data1['WORK_LIFE_BALANCE_SCORE']

In [41]:
print(X)

       FRUITS_VEGGIES  DAILY_STRESS  PLACES_VISITED  SUPPORTING_OTHERS  \
0                   3             2               2                  0   
1                   2             3               4                  8   
2                   2             3               3                  4   
3                   3             3              10                 10   
4                   5             1               3                 10   
...               ...           ...             ...                ...   
15967               3             3               0                  0   
15968               3             3               6                  7   
15969               4             3               0                 10   
15970               1             1              10                  2   
15971               5             4               0                 10   

       SOCIAL_NETWORK  ACHIEVEMENT  BMI_RANGE  TODO_COMPLETED  DAILY_STEPS  \
0                   5            

In [42]:
print(Y)
Y.head(20)

0        609.5
1        655.6
2        631.6
3        622.7
4        663.9
         ...  
15967    644.5
15968    714.9
15969    716.6
15970    682.0
15971    651.4
Name: WORK_LIFE_BALANCE_SCORE, Length: 15972, dtype: float64


0     609.5
1     655.6
2     631.6
3     622.7
4     663.9
5     722.3
6     727.2
7     676.2
8     702.8
9     634.4
10    610.1
11    618.6
12    686.4
13    689.6
14    639.7
15    720.4
16    673.5
17    707.6
18    727.8
19    687.1
Name: WORK_LIFE_BALANCE_SCORE, dtype: float64

DATA STANDARDISATION

In [43]:
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [44]:
standardized_data = scaler.transform(X)
print (standardized_data)

[[ 0.0535978  -0.57863435 -0.97619475 ... -0.40886969  0.42138426
   0.78753218]
 [-0.63957147  0.15241674 -0.37229512 ... -0.07735709  0.42138426
   0.78753218]
 [-0.63957147  0.15241674 -0.67424493 ... -1.0718949   0.42138426
   0.78753218]
 ...
 [ 0.74676707  0.15241674 -1.58009437 ...  1.24869332 -0.63751275
  -1.26978938]
 [-1.33274075 -1.30968543  1.43940376 ...  0.58566811 -0.63751275
   0.78753218]
 [ 1.43993635  0.88346782 -1.58009437 ... -0.74038229 -0.63751275
   0.78753218]]


In [45]:
X = standardized_data
Y = life_data1['WORK_LIFE_BALANCE_SCORE']
print(X)
print(Y)

[[ 0.0535978  -0.57863435 -0.97619475 ... -0.40886969  0.42138426
   0.78753218]
 [-0.63957147  0.15241674 -0.37229512 ... -0.07735709  0.42138426
   0.78753218]
 [-0.63957147  0.15241674 -0.67424493 ... -1.0718949   0.42138426
   0.78753218]
 ...
 [ 0.74676707  0.15241674 -1.58009437 ...  1.24869332 -0.63751275
  -1.26978938]
 [-1.33274075 -1.30968543  1.43940376 ...  0.58566811 -0.63751275
   0.78753218]
 [ 1.43993635  0.88346782 -1.58009437 ... -0.74038229 -0.63751275
   0.78753218]]
0        609.5
1        655.6
2        631.6
3        622.7
4        663.9
         ...  
15967    644.5
15968    714.9
15969    716.6
15970    682.0
15971    651.4
Name: WORK_LIFE_BALANCE_SCORE, Length: 15972, dtype: float64


#TRAIN TEST SPLIT


In [46]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [47]:
print(X.shape,X_train.shape,X_test.shape)

(15972, 17) (12777, 17) (3195, 17)


# MODEL TRAINING

In [46]:
#Linear regression


In [48]:
model = LinearRegression()
result=model.fit(X_train,Y_train)
res=model.score(X_train,Y_train)
print("Training Score:",res*100)

Training Score: 93.54147871211322


 #PREDICTION

In [49]:
predictions = result.predict(X_test)
reg_score=r2_score(Y_test,predictions)
print("Testing Score:",reg_score*100)

Testing Score: 93.6866889242879


In [50]:
X_train.shape

(12777, 17)

In [51]:
life=model.predict([[1,2,3,5,0,0,0,0,0,0,0,0,1,0,0,0,0]])
print(life)



[736.00075996]


In [52]:
print('Your Life-Balance Score is',life)


Your Life-Balance Score is [736.00075996]


In [52]:
#SAVING THE TRAINED MODEL

In [56]:
import pickle

In [57]:
pickle.dump(model,open('model.pkl','wb'))

In [58]:
#trained_model.sav is created in the miniproject folder.
#LOADING THE SAVED MODEL
loaded_model = pickle.load(open('model.pkl','rb'))#loading saved model